Config = {}

Config.Interactables = {
	'prop_bench_01a',
	'prop_bench_01b',
	'prop_bench_01c',
	'prop_bench_02',
	'prop_bench_03',
	'prop_bench_04',
	'prop_bench_05',
	'prop_bench_06',
	'prop_bench_05',
	'prop_bench_08',
	'prop_bench_09',
	'prop_bench_10',
	'prop_bench_11',
	'prop_fib_3b_bench',
	'prop_ld_bench01',
	'prop_wait_bench_01',
	'hei_prop_heist_off_chair',
	'hei_prop_hei_skid_chair',
	'prop_chair_01a',
	'prop_chair_01b',
	'prop_chair_02',
	'prop_chair_03',
	'prop_chair_04a',
	'prop_chair_04b',
	'prop_chair_05',
	'prop_chair_06',
	'prop_chair_05',
	'prop_chair_08',
	'prop_chair_09',
	'prop_chair_10',
	'v_club_stagechair',
	'prop_chateau_chair_01',
	'prop_clown_chair',
	'prop_cs_office_chair',
	'prop_direct_chair_01',
	'prop_direct_chair_02',
	'prop_gc_chair02',
	'prop_off_chair_01',
	'prop_off_chair_03',
	'prop_off_chair_04',
	'prop_off_chair_04b',
	'prop_off_chair_04_s',
	'prop_off_chair_05',
	'prop_old_deck_chair',
	'prop_old_wood_chair',
	'prop_rock_chair_01',
	'prop_skid_chair_01',
	'prop_skid_chair_02',
	'prop_skid_chair_03',
	'prop_sol_chair',
	'prop_wheelchair_01',
	'prop_wheelchair_01_s',
	'p_armchair_01_s',
	'p_clb_officechair_s',
	'p_dinechair_01_s',
	'p_ilev_p_easychair_s',
	'p_soloffchair_s',
	'p_yacht_chair_01_s',
	'v_club_officechair',
	'v_corp_bk_chair3',
	'v_corp_cd_chair',
	'v_corp_offchair',
	'v_ilev_chair02_ped',
	'v_ilev_hd_chair',
	'v_ilev_p_easychair',
	'v_ret_gc_chair03',
	'prop_ld_farm_chair01',
	'prop_table_04_chr',
	'prop_table_05_chr',
	'prop_table_06_chr',
	'v_ilev_leath_chr',
	'prop_table_01_chr_a',
	'prop_table_01_chr_b',
	'prop_table_02_chr',
	'prop_table_03b_chr',
	'prop_table_03_chr',
	'prop_torture_ch_01',
	'v_ilev_fh_dineeamesa',
	'v_ilev_fh_kitchenstool',
	'v_ilev_tort_stool',
	'v_ilev_fh_kitchenstool',
	'v_ilev_fh_kitchenstool',
	'v_ilev_fh_kitchenstool',
	'v_ilev_fh_kitchenstool',
	'hei_prop_yah_seat_01',
	'hei_prop_yah_seat_02',
	'hei_prop_yah_seat_03',
	'prop_waiting_seat_01',
	'prop_yacht_seat_01',
	'prop_yacht_seat_02',
	'prop_yacht_seat_03',
	'prop_hobo_seat_01',
	'prop_rub_couch01',
	'miss_rub_couch_01',
	'prop_ld_farm_couch01',
	'prop_ld_farm_couch02',
	'prop_rub_couch02',
	'prop_rub_couch03',
	'prop_rub_couch04',
	'p_lev_sofa_s',
	'p_res_sofa_l_s',
	'p_v_med_p_sofa_s',
	'p_yacht_sofa_01_s',
	'v_ilev_m_sofa',
	'v_res_tre_sofa_s',
	'v_tre_sofa_mess_a_s',
	'v_tre_sofa_mess_b_s',
	'v_tre_sofa_mess_c_s',
	'prop_roller_car_01',
	'prop_roller_car_02',
	'v_corp_bk_chair1', -- NEW
	'v_corp_bk_chair2',
	'v_corp_lazychair',
	'v_corp_lazychairfd',
	'v_corp_offchairfd',
	'v_corp_sidechair',
	'v_corp_sidechairfd',
	'v_ind_ss_chair01',
	'v_ind_ss_chair2',
	'v_ind_ss_chair3_cso',
	'v_ilev_chair02_ped',
	'v_ilev_hd_chair',
	'v_ilev_p_easychair',
	'v_res_d_armchair',
	'v_res_d_highchair',
	'v_res_fa_chair01',
	'v_res_fa_chair02',
	'v_res_fh_barcchair',
	'v_res_fh_easychair',
	'v_res_j_dinechair',
	'v_res_jarmchair',
	'v_res_m_armchair',
	'v_res_m_dinechair',
	'v_res_mbchair',
	'v_res_mp_stripchair',
	'v_res_study_chair',
	'v_res_tre_chair',
	'v_res_tre_officechair',
	'v_res_trev_framechair',
	'v_ret_chair',
	'v_ret_chair_white',
	'v_ret_fh_chair01',
	'v_ret_gc_chair01',
	'v_ret_gc_chair02',
	'v_ret_ps_chair',
	'v_serv_bs_barbchair',
	'v_serv_bs_barbchair2',
	'v_serv_bs_barbchair3',
	'v_serv_bs_barbchair5',
	'v_serv_ct_chair01',
	'v_serv_ct_chair02',
	'prop_off_chair_01',
	'prop_off_chair_03',
	'prop_off_chair_04',
	'prop_off_chair_04b',
	'prop_off_chair_05',
	'prop_sol_chair',
	'v_club_officechair',
	'v_corp_bk_chair3',
	'v_corp_cd_chair',
	'v_corp_offchair',
	'v_ret_gc_chair03',
	'prop_cs_office_chair',
	'prop_rock_chair_01',
	'prop_wheelchair_01',
	'p_yacht_chair_01_s',
	'prop_off_chair_04_s',
	'prop_direct_chair_01',
	'prop_direct_chair_02',
	'prop_ld_farm_chair01',
	'p_armchair_01_s',
	'p_clb_officechair_s',
	'p_dinechair_01_s',
	'p_ilev_p_easychair_s',
	'p_soloffchair_s',
	'prop_wheelchair_01_s',
	'prop_chair_01a',
	'prop_chair_01b',
	'prop_chair_02',
	'prop_chair_03',
	'prop_chair_04a',
	'prop_chair_04b',
	'prop_chair_05',
	'prop_chair_06',
	'prop_chair_07',
	'prop_chair_08',
	'prop_chair_09',
	'prop_chair_10',
	'prop_chateau_chair_01',
	'prop_clown_chair',
	'prop_old_deck_chair',
	'prop_old_wood_chair',
	'prop_old_wood_chair_lod',
	'v_16_low_lng_mesh_armchair',
	'v_club_barchair',
	'v_club_ch_armchair',
	'v_club_ch_briefchair',
	'v_club_stagechair',
	'v_club_vuarmchair',
	'v_med_fabricchair1',
	'v_med_p_deskchair',
	'v_med_p_easychair',
	'v_med_whickchair2',
	'v_med_whickerchair1',
	'prop_skid_chair_01',
	'prop_skid_chair_02',
	'prop_skid_chair_03',
	'prop_armchair_01',
	'prop_gc_chair02',
	'prop_yaught_chair_01',
	'apa_mp_h_din_chair_04',
	'apa_mp_h_din_chair_08',
	'apa_mp_h_din_chair_09',
	'apa_mp_h_din_chair_12',
	'apa_mp_h_stn_chairarm_01',
	'apa_mp_h_stn_chairarm_02',
	'apa_mp_h_stn_chairarm_03',
	'apa_mp_h_stn_chairarm_09',
	'apa_mp_h_stn_chairarm_11',
	'apa_mp_h_stn_chairarm_12',
	'apa_mp_h_stn_chairarm_13',
	'apa_mp_h_stn_chairarm_23',
	'apa_mp_h_stn_chairarm_24',
	'apa_mp_h_stn_chairarm_25',
	'apa_mp_h_stn_chairstool_12',
	'apa_mp_h_stn_chairstrip_01',
	'apa_mp_h_stn_chairstrip_02',
	'apa_mp_h_stn_chairstrip_03',
	'apa_mp_h_stn_chairstrip_04',
	'apa_mp_h_stn_chairstrip_05',
	'apa_mp_h_stn_chairstrip_06',
	'apa_mp_h_stn_chairstrip_07',
	'apa_mp_h_stn_chairstrip_08',
	'apa_mp_h_yacht_armchair_01',
	'apa_mp_h_yacht_armchair_03',
	'apa_mp_h_yacht_armchair_04',
	'apa_mp_h_yacht_strip_chair_01',
	'ba_prop_battle_club_chair_01',
	'ba_prop_battle_club_chair_02',
	'ba_prop_battle_club_chair_03',
	'bkr_prop_biker_boardchair01',
	'bkr_prop_biker_chair_01',
	'bkr_prop_biker_chairstrip_01',
	'bkr_prop_weed_chair_01a',
	'bkr_prop_biker_chairstrip_02',
	'bkr_prop_clubhouse_armchair_01a',
	'bkr_prop_clubhouse_chair_01',
	'bkr_prop_clubhouse_chair_03',
	'bkr_prop_clubhouse_offchair_01a',
	'xm_prop_x17_avengerchair',
	'xm_prop_x17_avengerchair_02',
	'xm_prop_x17_corp_offchair',
	'xm_int_lev_sub_chair_01',
	'xm_int_lev_sub_chair_02',
	'xm_lab_chairarm_02',
	'xm_lab_chairarm_03',
	'xm_lab_chairarm_11',
	'xm_lab_chairarm_12',
	'xm_lab_chairarm_24',
	'xm_lab_chairarm_25',
	'xm_lab_chairarm_26',
	'xm_lab_chairstool_12',
	'xm_lab_easychair_01',
	'xm_mp_h_stn_chairarm_13',
	'ex_mp_h_din_chair_04',
	'ex_mp_h_din_chair_08',
	'ex_mp_h_din_chair_09',
	'ex_mp_h_din_chair_12',
	'ex_mp_h_off_chairstrip_01',
	'ex_mp_h_off_easychair_01',
	'ex_mp_h_stn_chairarm_03',
	'ex_mp_h_stn_chairarm_24',
	'ex_mp_h_stn_chairstrip_01',
	'ex_mp_h_stn_chairstrip_010',
	'ex_mp_h_stn_chairstrip_011',
	'ex_mp_h_stn_chairstrip_05',
	'ex_mp_h_stn_chairstrip_07',
	'ex_prop_offchair_exec_01',
	'ex_prop_offchair_exec_02',
	'ex_prop_offchair_exec_03',
	'ex_prop_offchair_exec_04',
	'gr_prop_highendchair_gr_01a',
	'gr_prop_gr_chair02_ped',
	'gr_prop_gr_offchair_01a',
	'hei_prop_hei_skid_chair',
	'hei_prop_heist_off_chair',
	'hei_heist_din_chair_01',
	'hei_heist_din_chair_02',
	'hei_heist_din_chair_03',
	'hei_heist_din_chair_04',
	'hei_heist_din_chair_05',
	'hei_heist_din_chair_06',
	'hei_heist_din_chair_08',
	'hei_heist_din_chair_09',
	'hei_heist_stn_chairarm_01',
	'hei_heist_stn_chairarm_03',
	'hei_heist_stn_chairarm_04',
	'hei_heist_stn_chairarm_06',
	'hei_heist_stn_chairstrip_01',
	'ch_prop_casino_track_chair_01',
	'ch_prop_casino_chair_01a',
	'ch_prop_casino_chair_01b',
	'ch_prop_casino_chair_01c',
	'imp_prop_impexp_offchair_01a',
	'sm_prop_smug_offchair_01a',
	'sm_prop_offchair_smug_01',
	'sm_prop_offchair_smug_02',
	'sum_mp_h_yacht_armchair_01',
	'sum_mp_h_yacht_armchair_03',
	'sum_mp_h_yacht_armchair_04',
	'sum_mp_h_yacht_strip_chair_01',
	'vw_prop_vw_offchair_01',
	'vw_prop_vw_offchair_02',
	'vw_prop_vw_offchair_03',
	'vw_prop_casino_chair_01a',
	'vw_prop_casino_track_chair_01',
	'v_38_chairshadow',
	'v_43_officechair',
	'v_49_tat2chair',
	'v_50_chairsingle',
	'v_50_chairsingle002',
	'v_50_chairsingle003',
	'v_50_chairsingle020',
	'v_50_chairsingle021',
	'v_50_chairsingle022',
	'v_50_chairsingle023',
	'v_50_chairsingle12',
	'v_50_chairsingle18',
	'v_50_chairsingle19',
	'v_50_chairsingle2',
	'v_58_soloff_gchair',
	'v_58_soloff_gchair2',
	'v_58_soloff_offchair',
	'mp_b_din_chair_02',
	'mp_b_din_chair_03',
	'mp_b_din_chair_04',
	'mp_b_din_chair_05',
	'mp_b_din_chair_08',
	'mp_b_din_chair_09',
	'mp_b_stn_chairarm_01',
	'mp_b_stn_chairarm_03',
	'mp_b_stn_chairarm_04',
	'mp_b_stn_chairarm_06',
	'mp_b_stn_chairstrip_01',
	'apa_mpa2_chairarm',
	'apa_mpa2_din_chair_00',
	'apa_mpa2_din_chair_01',
	'apa_mpa2_din_chair_02',
	'apa_mpa2_din_chair_03',
	'apa_mpa2_din_chair_04',
	'apa_mpa2_din_chair_05',
	'apa_mpa2_din_chair_06',
	'apa_mpa2_din_chair_07',
	'apa_mpa6_chairarm',
	'apa_mpa6_din_chair_00',
	'apa_mpa6_din_chair_01',
	'apa_mpa6_din_chair_02',
	'apa_mpa6_din_chair_03',
	'apa_mpa6_din_chair_04',
	'apa_mpa6_din_chair_05',
	'apa_mpa6_din_chair_06',
	'apa_mpa6_din_chair_07',
	'apa_chairstrip_0x',
	'bkr_int_02_chair_bar_table_01',
	'bkr_int_02_chair_bar_table_02',
	'bkr_int_02_strip_chair',
	'ex_office2b_stripchair1',
	'ex_office2b_stripchair2',
	'ex_office_03b_stripchair1',
	'ex_office_03b_stripchair2',
	'ex_office_03c_chairstrip_01',
	'ex_office_03c_recepchair_1',
	'ex_office_03c_recepchair_2',
	'ex_office_03c_stripchair_02',
	'h4_int_04_armchair_fireplace',
	'h4_int_04_desk_chair',
	'h4_int_05_wooden_chairs_2',
	'h4_prop_battle_club_chair_01',
	'h4_prop_battle_club_chair_02',
	'h4_prop_battle_club_chair_03',
	'h4_prop_h4_chair_01a',
	'h4_prop_h4_weed_chair_01a',
	'h4_int_lev_sub_chair_01',
	'h4_int_lev_sub_chair_02',
	'h4_mp_h_yacht_armchair_01',
}

Config.Sitable = {
	prop_bench_01a 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_01b 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_01c 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_02 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_03 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_04 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_05 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_06 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_07 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_08 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_09 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.31, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_10 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_bench_11 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_fib_3b_bench 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_ld_bench01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_wait_bench_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_club_stagechair 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_prop_heist_off_chair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_prop_hei_skid_chair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_01a 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_01b 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_02 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_03 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_04a 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_04b 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_05 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_06 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_07 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_08 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_09 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_10 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chateau_chair_01 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_clown_chair 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_cs_office_chair 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_direct_chair_01 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_direct_chair_02 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_gc_chair02 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_03 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_04 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_04b 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_04_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_05 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0},
	prop_old_deck_chair 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_old_wood_chair 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_rock_chair_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_skid_chair_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_skid_chair_02 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_skid_chair_03 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_sol_chair 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_wheelchair_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_wheelchair_01_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_armchair_01_s 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_clb_officechair_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_dinechair_01_s 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_ilev_p_easychair_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_soloffchair_s 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_yacht_chair_01_s 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_club_officechair 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_bk_chair3 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_cd_chair 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_offchair 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_chair02_ped 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_hd_chair 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_p_easychair 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_gc_chair03 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_ld_farm_chair01 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_table_04_chr 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.56, forwardOffset = 0.0, leftOffset = 0.0},
	prop_table_05_chr 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_table_06_chr 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_leath_chr 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_table_01_chr_a 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_table_01_chr_b 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_table_02_chr 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_table_03b_chr 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_table_03_chr 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_torture_ch_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_fh_dineeamesa 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_fh_kitchenstool 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_tort_stool 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_prop_yah_seat_01 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_prop_yah_seat_02 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_prop_yah_seat_03 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_waiting_seat_01 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_yacht_seat_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_yacht_seat_02 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_yacht_seat_03 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_hobo_seat_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.65, forwardOffset = 0.0, leftOffset = 0.0},
	prop_rub_couch01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	miss_rub_couch_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_ld_farm_couch01 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_ld_farm_couch02 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_rub_couch02 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_rub_couch03 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_rub_couch04 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_lev_sofa_s 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_res_sofa_l_s 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_v_med_p_sofa_s 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_yacht_sofa_01_s					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_m_sofa 						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_tre_sofa_s 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_tre_sofa_mess_a_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_tre_sofa_mess_b_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_tre_sofa_mess_c_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_roller_car_01 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_roller_car_02 					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_gc_chair02					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_serv_ct_chair02					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_bk_chair1					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_bk_chair2					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_lazychair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_lazychairfd					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_offchairfd					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_sidechair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_sidechairfd					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ind_ss_chair01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ind_ss_chair2						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ind_ss_chair3_cso					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_chair02_ped					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_hd_chair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ilev_p_easychair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_d_armchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_d_highchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_fa_chair01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_fa_chair02					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_fh_barcchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_fh_easychair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_j_dinechair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_jarmchair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_m_armchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_m_dinechair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_mbchair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_mp_stripchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_study_chair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_tre_chair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_tre_officechair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_res_trev_framechair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_chair							= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_chair_white					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_fh_chair01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_gc_chair01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_gc_chair02					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_ps_chair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_serv_bs_barbchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_serv_bs_barbchair2				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_serv_bs_barbchair3				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_serv_bs_barbchair5				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_serv_ct_chair01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_serv_ct_chair02					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_03					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_04					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_04b					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_05					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_sol_chair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_club_officechair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_bk_chair3					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_cd_chair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_corp_offchair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_ret_gc_chair03					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_cs_office_chair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_rock_chair_01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_wheelchair_01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_yacht_chair_01_s					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_off_chair_04_s					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_direct_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_direct_chair_02				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_ld_farm_chair01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_armchair_01_s						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_clb_officechair_s					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_dinechair_01_s					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_ilev_p_easychair_s				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	p_soloffchair_s						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_wheelchair_01_s				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_01a						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_01b						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_02						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_03						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_04a						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_04b						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_05						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_06						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_07						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_08						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_09						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chair_10						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_chateau_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_clown_chair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_old_deck_chair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_old_wood_chair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_old_wood_chair_lod				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_16_low_lng_mesh_armchair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_club_barchair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_club_ch_armchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_club_ch_briefchair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_club_stagechair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_club_vuarmchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_med_fabricchair1					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_med_p_deskchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_med_p_easychair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_med_whickchair2					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_med_whickerchair1					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_skid_chair_01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_skid_chair_02					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_skid_chair_03					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_armchair_01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_gc_chair02						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	prop_yaught_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_din_chair_04				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_din_chair_08				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_din_chair_09				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_din_chair_12				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_03			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_09			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_11			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_12			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_13			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_23			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_24			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairarm_25			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstool_12			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstrip_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstrip_02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstrip_03			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstrip_04			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstrip_05			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstrip_06			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstrip_07			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_stn_chairstrip_08			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_yacht_armchair_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_yacht_armchair_03			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_yacht_armchair_04			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mp_h_yacht_strip_chair_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ba_prop_battle_club_chair_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ba_prop_battle_club_chair_02		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ba_prop_battle_club_chair_03		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_biker_boardchair01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_biker_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_biker_chairstrip_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_weed_chair_01a				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_biker_chairstrip_02		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_clubhouse_armchair_01a		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_clubhouse_chair_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_clubhouse_chair_03			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_prop_clubhouse_offchair_01a		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_prop_x17_avengerchair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_prop_x17_avengerchair_02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_prop_x17_corp_offchair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_int_lev_sub_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_int_lev_sub_chair_02				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_chairarm_02					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_chairarm_03					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_chairarm_11					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_chairarm_12					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_chairarm_24					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_chairarm_25					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_chairarm_26					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_chairstool_12				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_lab_easychair_01					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	xm_mp_h_stn_chairarm_13				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_din_chair_04				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_din_chair_08				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_din_chair_09				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_din_chair_12				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_off_chairstrip_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_off_easychair_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_stn_chairarm_03				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_stn_chairarm_24				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_stn_chairstrip_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_stn_chairstrip_010			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_stn_chairstrip_011			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_stn_chairstrip_05			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_mp_h_stn_chairstrip_07			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_prop_offchair_exec_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_prop_offchair_exec_02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_prop_offchair_exec_03			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_prop_offchair_exec_04			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	gr_prop_highendchair_gr_01a			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	gr_prop_gr_chair02_ped				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	gr_prop_gr_offchair_01a				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_prop_hei_skid_chair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_prop_heist_off_chair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_din_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_din_chair_02				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_din_chair_03				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_din_chair_04				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_din_chair_05				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_din_chair_06				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_din_chair_08				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_din_chair_09				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_stn_chairarm_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_stn_chairarm_03			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_stn_chairarm_04			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_stn_chairarm_06			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	hei_heist_stn_chairstrip_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ch_prop_casino_track_chair_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ch_prop_casino_chair_01a			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ch_prop_casino_chair_01b			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ch_prop_casino_chair_01c			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	imp_prop_impexp_offchair_01a		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	sm_prop_smug_offchair_01a			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	sm_prop_offchair_smug_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	sm_prop_offchair_smug_02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	sum_mp_h_yacht_armchair_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	sum_mp_h_yacht_armchair_03			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	sum_mp_h_yacht_armchair_04			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	sum_mp_h_yacht_strip_chair_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	vw_prop_vw_offchair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	vw_prop_vw_offchair_02				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	vw_prop_vw_offchair_03				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	vw_prop_casino_chair_01a			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	vw_prop_casino_track_chair_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_38_chairshadow					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_43_officechair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_49_tat2chair						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle002					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle003					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle020					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle021					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle022					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle023					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle12					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle18					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle19					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_50_chairsingle2					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_58_soloff_gchair					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_58_soloff_gchair2					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	v_58_soloff_offchair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_din_chair_02					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_din_chair_03					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_din_chair_04					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_din_chair_05					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_din_chair_08					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_din_chair_09					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_stn_chairarm_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_stn_chairarm_03				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_stn_chairarm_04				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_stn_chairarm_06				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	mp_b_stn_chairstrip_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_chairarm					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_din_chair_00				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_din_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_din_chair_02				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_din_chair_03				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_din_chair_04				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_din_chair_05				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_din_chair_06				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa2_din_chair_07				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_chairarm					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_din_chair_00				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_din_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_din_chair_02				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_din_chair_03				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_din_chair_04				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_din_chair_05				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_din_chair_06				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_mpa6_din_chair_07				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	apa_chairstrip_0x					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_int_02_chair_bar_table_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_int_02_chair_bar_table_02		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	bkr_int_02_strip_chair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_office2b_stripchair1				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_office2b_stripchair2				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_office_03b_stripchair1			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_office_03b_stripchair2			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_office_03c_chairstrip_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_office_03c_recepchair_1			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_office_03c_recepchair_2			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	ex_office_03c_stripchair_02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_int_04_armchair_fireplace		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_int_04_desk_chair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_int_05_wooden_chairs_2			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_prop_battle_club_chair_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_prop_battle_club_chair_02		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_prop_battle_club_chair_03		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_prop_h4_chair_01a				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_prop_h4_weed_chair_01a			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_int_lev_sub_chair_01				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_int_lev_sub_chair_02				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
	h4_mp_h_yacht_armchair_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0},
}

